(() => {
 'use strict';
 const CONFIG={"app": "smallhelpnow", "endpoint": "smallhelpnow-payments", "choices": {"1": {"amount": 100, "label": "One-time support"}, "1.99": {"amount": 199, "label": "One-time support"}, "4.99": {"amount": 499, "label": "One-time support"}}, "note": "Your voluntary contribution supports development and operation of useful projects."};
 const endpoint='https://bkyuyqicybqqifenhhux.supabase.co/functions/v1/'+CONFIG.endpoint;
 const params=new URLSearchParams(location.search),option=CONFIG.app==='billsavings_ai'?params.get('plan'):CONFIG.app==='smallhelpnow'?params.get('amount'):'pro';
 const queryHash=new URLSearchParams(location.hash.slice(1));
 if(CONFIG.app==='billsavings_ai'&&(params.has('session_id')||queryHash.has('access_token')||queryHash.has('refresh_token')||queryHash.has('error')||queryHash.has('error_code'))){const u=new URL('/start.html',location.origin);u.search=params.has('session_id')?'?checkout=return&session_id='+encodeURIComponent(params.get('session_id')):'?access=ready';u.hash=location.hash;location.replace(u.href);return;}
 if(!Object.hasOwn(CONFIG.choices,option)){location.replace(CONFIG.app==='billsavings_ai'?'/start.html':'/');return;}
 const status=document.getElementById('checkoutStatus'),retry=document.getElementById('checkoutRetry'),manual=document.getElementById('checkoutContinue'),qrButton=document.getElementById('checkoutQr');
 document.getElementById('selectedPlan').textContent=CONFIG.choices[option].label;document.getElementById('selectedPrice').textContent='$'+(CONFIG.choices[option].amount/100).toFixed(2)+(CONFIG.app==='billsavings_ai'?' / month':' one-time');
 const timeout=p=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error('account_check_unavailable')),12000))]);
 const request=async body=>{
   const headers={'Content-Type':'application/json'};
   if(CONFIG.app==='billsavings_ai'){let saved=false;try{saved=!!sessionStorage.getItem('billsavings.account.v1');}catch{}if(saved){const {supabase}=await timeout(import('./account-session.js'));const {data,error}=await timeout(supabase.auth.getSession());if(error)throw new Error('account_check_unavailable');if(data.session?.access_token)headers.Authorization='Bearer '+data.session.access_token;}}
   const response=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(30000),cache:'no-store',referrerPolicy:'no-referrer'});const data=await response.json();if(!response.ok)throw new Error(data.error||'checkout_unavailable');return data;
 };
 const normalKey=CONFIG.app+'.checkout-request.v1';let normal;
 try{normal=JSON.parse(sessionStorage.getItem(normalKey)||'null');if(normal?.option!==option||normal.expires<Date.now()||!/^[a-f0-9]{64}$/.test(normal.token||'')||!/^[a-f0-9-]{36}$/i.test(normal.attempt||''))normal=null;}catch{}
 if(!normal){normal={option,token:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),attempt:crypto.randomUUID(),expires:Date.now()+1800000};try{sessionStorage.setItem(normalKey,JSON.stringify(normal));}catch{}}
 const remember=(data,token)=>{if(CONFIG.app==='billsavings_ai'){try{localStorage.setItem('billsavings.purchase-plan',JSON.stringify({plan:option,expires:Date.now()+3600000}));}catch{}}if(CONFIG.app==='repaircostmatch')localStorage.setItem('rcm.checkout-owner.v1',JSON.stringify({session_id:data.session_id,token,expires_at:data.expires_at}));};
 const errorMessage=error=>{if(error.message==='already_subscribed'){location.replace('/start.html?access=ready');return;}status.textContent=['sign_in_required','account_check_unavailable'].includes(error.message)?'We could not check your saved account. Sign in before paying again.':'Checkout is temporarily unavailable. Retry this request before starting another payment.';retry.hidden=false;};
 const make=async (draft,qr)=>{const data=await request({action:'checkout',...(CONFIG.app==='billsavings_ai'?{plan:draft.option}:CONFIG.app==='smallhelpnow'?{amount:draft.option}:{offer:'pro'}),token:draft.token,attempt:draft.attempt,...(qr?{checkout_channel:'qr'}:{})});remember(data,draft.token);return data;};
 const q=new PaymentQr({key:CONFIG.app+'.qr.v1',choices:CONFIG.choices,note:CONFIG.note,create:d=>make(d,true),status:(action,p)=>request({action,session_id:p.session_id,token:p.token}),onPaid:async(data,p)=>{if(CONFIG.app==='billsavings_ai'){location.assign('/start.html?checkout=success&session_id='+encodeURIComponent(p.session_id));}else if(CONFIG.app==='repaircostmatch'){location.assign('/?pro_live=success&session_id='+encodeURIComponent(p.session_id));}else{status.textContent='Thank you! Your support payment is confirmed.';manual.hidden=true;qrButton.hidden=true;}},onError:errorMessage,onCancelled:()=>{status.textContent='Checkout cancelled. Choose QR or card to create a new payment.';sessionStorage.removeItem(normalKey);normal.attempt=crypto.randomUUID();qrButton.hidden=false;retry.hidden=false;}});
 let busy=false;
 async function checkout(){if(q.hasPending)return q.resume();if(busy)return;busy=true;retry.hidden=true;status.textContent='Opening secure Stripe checkout…';try{const data=await make(normal,false),u=new URL(data.url);if(u.origin!=='https://checkout.stripe.com'||u.username||u.password||u.pathname!=='/c/pay/'+data.session_id)throw new Error('invalid_checkout');manual.href=u.href;manual.hidden=false;location.assign(u.href);}catch(error){errorMessage(error);}finally{busy=false;}}
 retry.addEventListener('click',()=>params.get('method')==='qr'?q.prepare(option):checkout());qrButton.addEventListener('click',()=>q.prepare(option));
 if(q.hasPending){qrButton.hidden=false;void q.resume();}else if(params.get('method')==='qr'){qrButton.hidden=false;status.textContent='Scan the QR or open the same Stripe checkout here.';void q.prepare(option);}else void checkout();
})();
